version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend_container
    ports: 
      - "4000:4000"
    depends_on:
      - "mongo"
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  