export const PROFILES_LIST_REQUEST = "PROFILES_LIST_REQUEST";
export const PROFILES_LIST_SUCCESS = "PROFILES_LIST_SUCCESS";
export const PROFILES_LIST_FAIL = "PROFILES_LIST_FAIL";

export const PROFILE_CREATE_REQUEST = "PROFILE_CREATE_REQUEST";
export const PROFILE_CREATE_SUCCESS = "PROFILE_CREATE_SUCCESS";
export const PROFILE_CREATE_FAIL = "PROFILE_CREATE_FAIL";

export const PROFILES_UPDATE_REQUEST = "PROFILES_UPDATE_REQUEST";
export const PROFILES_UPDATE_SUCCESS = "PROFILES_UPDATE_SUCCESS";
export const PROFILES_UPDATE_FAIL = "PROFILES_UPDATE_FAIL";

export const PROFILES_DELETE_REQUEST = "PROFILES_DELETE_REQUEST";
export const PROFILES_DELETE_SUCCESS = "PROFILES_DELETE_SUCCESS";
export const PROFILES_DELETE_FAIL = "PROFILES_DELETE_FAIL";
